### ISSUE TITLE
doesn't work inside Modal

### ISSUE THREAD

**Issue by mschipperheyn** [instea/react-native-popup-menu#1]
Just like react-native-menu, this doesn't work inside a Modal. It shows up behind the modal I think.

Any suggestions?

**Comment by sodik82** [comment]
the problem is with React Native "z-index" handling. However solution is to use (additional) `MenuContext` inside the modal ... that way the context menu will be rendered in proper place.

Later on we will provide working example but this should help you.

**Comment by mschipperheyn** [comment]
Great suggestion! Looking forward to an example buy I assume it has to  be the root of the render method or some tag that encloses the menu tags

**Comment by madox2** [comment]
Modal contains it's own react native root therefore you need to add `MenuContext` to it as mentioned by @sodik82. I have added an [example](/instea/react-native-popup-menu/blob/master/examples/ModalExample.js) how to use it with modal.

**Comment by mschipperheyn** [comment]
Works!
