### ISSUE TITLE
how to change arrow backgroundColor

### ISSUE THREAD

**Issue by Sobranier** [instea/react-native-popup-menu#102]
if I set some attributes like this to change the menu's backgroundColor,I cannot change the arrow's color. what should I do ?
```
MenuOptions
  optionsWrapper: {
    backgroundColor: 'transparent',
  },
  optionsContainer: {
    backgroundColor: 'transparent',
  }
```

```
MenuOption
  optionWrapper: {
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
  }
```

<img width="98" alt="2018-05-29 4 39 21" src="https://user-images.githubusercontent.com/7440073/40648049-fd9be4b6-635f-11e8-9844-60a82ce17fc4.png">

**Comment by madox2** [comment]
Hi, it should be possible by playing around with `anchorStyle` property of [popover](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#popover).

**Comment by Sobranier** [comment]
@madox2 Thx ，it works
