### ISSUE TITLE
Menu opened true not showing tooltip

### ISSUE THREAD

**Issue by ranvir-gorai** [instea/react-native-popup-menu#105]
If you have question about the usage of the library, please ask question on StackOverflow with tag [react-native-popup-menu](http://stackoverflow.com/questions/tagged/react-native-popup-menu). We are subscribed to it but it also allows community to help you if we are busy.

If you have found a bug, please describe your problem and expected behaviour. Additionally let us know library version, platform on which the problem happens and if possible some code snipets reproducing problem.

if I setup tool tip opened true it is not showing if i render this tooltip is not showing

```
 <Menu
          renderer={Popover}
          **opened={true}**
          rendererProps={{
            anchorStyle: styles.firstTimeToolTipWrapper,
            preferredPlacement: 'top',
            placement: 'top'
          }}
        >
```
is there any provision to auto hide tool tip, or insted of wrapping triger can we render it as component for tool tip purpose like web

**Comment by sodik82** [comment]
hi, tooltip on the web usually triggered with onMouseOver, however on mobile there is no such thing. We need the trigger at least to know the position. 
If you use `opened={true}`, it means that it will stay opened for ever, however, it you want to make it closable, either check for onBackdropPress callback or if you just want to make it open on mount, use refs.
