### ISSUE TITLE
iPhoneX SafeArea

### ISSUE THREAD

**Issue by axelnormand** [instea/react-native-popup-menu#108]
Thank you for such a great library.

Just noticed a small bug. If the ContextMenu is near the bottom then the bottom menu item is probably too far down the screen on the iPhone X.
Should `ContextMenu.computePosition` take account of the top notch / bottom curved bit in it's calculation of top?

Or should the absolute position calc be relative to inside a SafeAreaView?

Thanks

**Comment by sodik82** [comment]
thanks, we will take a lot into it.

**Comment by sodik82** [comment]
@axelnormand  can you try `0.14`?
