### ISSUE TITLE
The MenuOptions look like have marginTop

### ISSUE THREAD

**Issue by cuiyueshuai** [instea/react-native-popup-menu#11]
Hi, I used the react-native-popop-menu, find the MenuOptions wasn't follow the MenuTrigger，look like MenuOptions exist marginTop, and I don't know how to set it can remove the margin, this.is my page and code 
![screen shot 2016-11-15 at 2 55 25 pm](https://cloud.githubusercontent.com/assets/13741688/20296154/2237bb86-ab44-11e6-99a3-92e3e67621ff.png)
![screen shot 2016-11-15 at 3 02 19 pm](https://cloud.githubusercontent.com/assets/13741688/20296228/8e5fe112-ab44-11e6-97af-2f69a9fc975f.png)

**Comment by sodik82** [comment]
thanks for reporting. can you try to put your `MenuContext` to the "top" of your application - somewhere on top of your (I believe it is) your navigation? similar to the issue #10 . Just let us know if something like that helped.

**Comment by cuiyueshuai** [comment]
Thank you! I resolve the problem, I put my navigationBar to the MenuContext and MenuContext in the Top of my Application, you are right!

**Comment by sodik82** [comment]
hi, we made small improvements in `0.5.8` that could better handle your case.

note: `MenuContext` still should be on the top of your application to work correctly.
