### ISSUE TITLE
Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

### ISSUE THREAD

**Issue by 28harishkumar** [instea/react-native-popup-menu#110]
Every time I click on `MenuTrigger`, I am getting warning (even with examples provided in this github repo)
```  Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks. ```

react-native-cli: 2.0.1
react-native: 0.55.4
Android Studio: 3.1.3
Android Studio SDK: 26.0.1
Android Version: 5.1.1

**Comment by sodik82** [comment]
I think it is not directly related to popup menu. See issue #93 for more details.
