### ISSUE TITLE
Failed to build with babel 7 (react-native 0.56.0-rc.3)

### ISSUE THREAD

**Issue by jacargentina** [instea/react-native-popup-menu#111]
When starting to test the newest react-native release candidate, I've found this error

<img width="907" alt="captura de pantalla 2018-06-22 a la s 19 39 44" src="https://user-images.githubusercontent.com/517228/41801984-3e1f98b4-7654-11e8-9139-59eb9dff8d43.png">

There is a trailing comma there, which babel 7 complains; can it be removed please? Cheers!

**Comment by sodik82** [comment]
thanks for reporting, can you try with `0.13.2`?

**Comment by yonedev** [comment]
I had same problem. Update from 0.13.1 to 0.13.3 and fix
