### ISSUE TITLE
Popup needs double tap to select

### ISSUE THREAD

**Issue by Djinne** [instea/react-native-popup-menu#113]
Hi there,

When the menu popups up, I need to click on the box to "focus" it before selecting an item.

**Comment by Djinne** [comment]
Woops, just needed a blur function on input

**Comment by tamdesktop** [comment]
@Djinne I got same issue. I'm using popup to display suggestions on search input. User must to double tap to select a suggestion (first tap: lost focus on text input, second tap: select item on popup menu)

Can you share your idea?

**Comment by Djinne** [comment]
- make sure to blur any textinput that triggers a popup, 
- use focus() on the ref of the textinput on your search input once the popup is open
