### ISSUE TITLE
How to auto close popup menu when click Back Android Device

### ISSUE THREAD

**Issue by thuytony** [instea/react-native-popup-menu#114]
Hello. I can't auto closepopup menu when I click button back Android device.. I try set state with method opened, but it's don't working. Can anyone help me? Thanks you so much.

**Comment by sodik82** [comment]
Have you tried asking on Stackoverflow?

Or check the documentation about [backHandler](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#properties)

**Comment by thuytony** [comment]
Sorry. I am beginner React Native. I have read backHandler.
I try set backHandler={true}, but it's don't work :(
I do not know where I'm wrong. Can you give me an example?

**Comment by sodik82** [comment]
https://github.com/instea/react-native-popup-menu/blob/master/examples/CloseOnBackExample.js
