### ISSUE TITLE
Cannot resolve withMenuContext

### ISSUE THREAD

**Issue by kstott** [instea/react-native-popup-menu#120]
I'm using RN .56 and react-native-popup-menu@0.14.0.

Everything works fine, except for this:

import {withMenuContext} from 'react-native-popup-menu'

This is always identified as an unresolved symbol. I see that its being export in src/index.js. I can use all of the other exported symbols. Any ideas what the issue is?

**Comment by sodik82** [comment]
Hi. I have just tried MenuMethodsExample.js in new RN 0.56.0 project and it is working. Can you try it out or share more details?

**Comment by sodik82** [comment]
if anyone has more info - maybe some setup in your project - will reopen.
