### ISSUE TITLE
Popover {placement: bottom} render an empty box

### ISSUE THREAD

**Issue by wesleyamaro** [instea/react-native-popup-menu#121]
Hey Guys, 

When I change the  renderProps "placement" from left to bottom using Popover, the component does not render, just appear the box without content. If I put "left" the component works well.

```javascript
import {
	Menu,
	MenuOptions,
	MenuOption,
	MenuTrigger,
	renderers
} from 'react-native-popup-menu';

<Menu
     renderer={renderers.Popover}
     rendererProps={{ placement: 'bottom' }}
>
```

Note: react-native-popup-menu: "^0.14.0"

I do not know If I am doing something wrong or the component is not working on that way.

**Comment by creambyemute** [comment]
@wesleyamaro I'm using PopOver + bottom placement and it works fine for me with RN 0.55.4 or 0.57.4 and version `0.14.1` of this library.

![popover](https://user-images.githubusercontent.com/3519121/48272995-431fd680-e440-11e8-8c82-72b595ad4380.png)
