### ISSUE TITLE
Does the MenuTrigger has onLongPress prop?

### ISSUE THREAD

**Issue by leiz-me** [instea/react-native-popup-menu#123]
I see that MenuTrigger has onPress prop, but looks like onLongPress not work here?

**Comment by sodik82** [comment]
no, currently not. but I think you could use custom [TriggerTouchableComponent](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#custom-styles-1)  create, which onLongPress as onPress expose.

**Comment by leiz-me** [comment]
@sodik82 how can I customize TriggerTouchableComponent create? I looked into the examples but find no clue.

**Comment by leiz-me** [comment]
I checked the code you mentioned.
Since what I hope to do is to expose a prop onLongPress which is the default props from touchable component of RN, why not just add some lines of code on MenuTrigger.js ?

Just follow the way how onPress works there looks good enough, I guess.
Am I correct?

**Comment by leiz-me** [comment]
Prop is one option. But I am thinking if I really need to do that switch.

**Comment by sodik82** [comment]
how would you do "both" at the same time?

**Comment by leiz-me** [comment]
Let's say I have a Home view which has an plus "+" button on the right top of the header.
When I tap the "+", it shows a popover menu with some options, like adding item, adding image or something else. But also, for user experience, I want this "+" button has a shortcut for users to get to the adding item view, so here I would want to have a longPress prop to handle the navigation.

So I think THAT SWITCH might not be necessary, just like the reason why text and touchable component have two kinds of onPress,  just one option for developers to handle how to present the navigation or any expected requirements.

**Comment by sodik82** [comment]
ok, now I understand. if you want to do menu un-related action on longpress (e.g. navigation), you can use `triggerTouchable` prop (see doc).

**Comment by leiz-me** [comment]
What I can find from the doc is that triggerTouchable is in the customStyles of MenuTrigger, how can I use that to do the navigation?

**Comment by sodik82** [comment]
something like
```
<MenuTrigger customStyles={{ triggerTouchable: { onLongPress: () => console.log('navigate') }}} > 
```

**Comment by leiz-me** [comment]
It worked, thank you.
I suggest this part should be added to the doc, because customStyles just looks like styles, kind of misunderstanding.

**Comment by sodik82** [comment]
well, yeah, it is meant for styling :)

**Comment by iamamanprajapati** [comment]
@sodik82 
I really Thanks sir,
