### ISSUE TITLE
Clarification: If we upgrade the react-native to 0.56 all the implemented file in iOS get deleted or not

### ISSUE THREAD

**Issue by nihp** [instea/react-native-popup-menu#126]
I  used react-native-popup-menu to show the popup window. Here I upgraded my react-native version 0.53.3 to 0.56.0. 

After updating the version ios folder get deleted and my all implementation (custom font support, bundle id, fastlane support) all are gets  deleted. Is it is a correct behaviour. Kindly clarify

**Comment by sodik82** [comment]
I am afraid that popup menu is not responsible for deleting files during RN upgrade.
