### ISSUE TITLE
Transpile to ES5 for usage on web

### ISSUE THREAD

**Issue by joncursi** [instea/react-native-popup-menu#127]
Right now it looks like ES6 is being published to NPM. This works for react-native, but doesn't work for using this on the web via libraries like react-native-web. 

```
 error  in ./node_modules/react-native-popup-menu/src/helpers.js

Module parse failed: Unexpected token (98:15)
You may need an appropriate loader to handle this file type.
| 
|       render() {
>         return <Component {...this.props} ref={this.onRef} />
|       }
| 
```

**Comment by sodik82** [comment]
thanks for the notice. is anyone willing to do PR? :)

**Comment by JesseRWeigel** [comment]
I would love to have this feature for a project I am working on! I will try and create a PR sometime early next week.

**Comment by sodik82** [comment]
thanks, looking forward to it.
