### ISSUE TITLE
require cycle index.js-->menu.js-->index.js

### ISSUE THREAD

**Issue by liukefu2050** [instea/react-native-popup-menu#128]
If you have question about the usage of the library, please ask question on StackOverflow with tag [react-native-popup-menu](http://stackoverflow.com/questions/tagged/react-native-popup-menu). We are subscribed to it but it also allows community to help you if we are busy.

If you have found a bug, please describe your problem and expected behaviour. Additionally let us know library version, platform on which the problem happens and if possible some code snipets reproducing problem.

require cycle index.js-->menu.js-->index.js
require cycles are allowed,but can result in uninitialized values.

**Comment by sodik82** [comment]
thanks, it really looks like it can be written without cycles. will check it more deeply.

**Comment by gson2019** [comment]
any updates for this? I still got this warning

**Comment by sodik82** [comment]
where do you get warning?

**Comment by gson2019** [comment]
Hi Sodik, it happens when the page with MenuProvider as the most outside tag is rendred.

**Comment by abarisic86** [comment]
There is a fix in 0.14.1 but even with that version, I'm getting this warning.

`Require cycle: node_modules/react-native-popup-menu/src/Menu.js -> node_modules/react-native-popup-menu/src/MenuOptions.js -> node_modules/react-native-popup-menu/src/MenuProvider.js -> node_modules/react-native-popup-menu/src/MenuPlaceholder.js -> node_modules/react-native-popup-menu/src/logger.js -> node_modules/react-native-popup-menu/src/Menu.js`

**Comment by sodik82** [comment]
sorry, I meant where can I see this warning? which version of RN?

**Comment by gson2019** [comment]
I'm using 0.57.4 RN, I got exact the same warnings as @abarisic86 got.

**Comment by sodik82** [comment]
you can try `0.14.2`
