### ISSUE TITLE
How to trigger menu other than clicking MenuTrigger?

### ISSUE THREAD

**Issue by jjdp** [instea/react-native-popup-menu#13]

**Comment by madox2** [comment]
There are several ways how to do this. One is to obtain `<MenuContext />` ref and call `openMenu` method on it:

```jsx
<MenuContext ref={mc => this.menuContext = mc}>
  <Menu name='myMenu'>
    ...
  </Menu>
</MenuContext>

// then you can call
this.menuContext.openMenu('myMenu');
```

These methods are documented in [api section](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#methods-menuactions-context). Methods are also exposed by `<MenuContext />` to the `menuActions` child [context](https://facebook.github.io/react/docs/context.html).

Furthermore you can use menu as controlled/declarative component where `opened` property indicates whether menu is opened or not. See the [controlled example](https://github.com/instea/react-native-popup-menu/blob/master/examples/ControlledExample.js)

**Comment by jjdp** [comment]
tnx

**Comment by huiming1313** [comment]
@jjdp 
Do you have the example of this?
I'm using react navigation, i would like to open the menu by clicking the HeaderRight  component but i not sure how to do this.

```
static navigationOptions = {
        headerTitle: 'News',
        headerRight: (
          <TouchableOpacity style={{ paddingLeft:15, paddingRight:15 }} onPress={() => // trigger open menu from here  }>
              <Icon name="more-vert" size={30} color="black" />
          </TouchableOpacity>
        )
    }
```

I've wrap the navigation within menu context
```
<Provider store={store}>
          <MenuContext ref={mc => this.menuContext = mc} style={{ flex: 1 }}>
              <AppWithNavigationState />
          </MenuContext>
      </Provider>

```

**Comment by sodik82** [comment]
As mentioned above - just call `this.menuContext.openMenu('myMenu');`

Or another slightly different option is https://github.com/instea/react-native-popup-menu/blob/143cf6a2c7f371d6028f1174391add2b476c3361/examples/MenuMethodsExample.js

**Comment by alvaro1728** [comment]
It might be worth mentioning that `this.menuContext.openMenu('myMenu');` didn't work for me until I added a  `MenuTrigger` inside my menu:

```
<Menu name="myMenu">
    <MenuTrigger />
```
Cheers!
