### ISSUE TITLE
MenuContext is not fully displayed in the drop-down menu in <View style={{flex Direction:'row',}>.

### ISSUE THREAD

**Issue by honeyzhaoAliyun** [instea/react-native-popup-menu#136]
MenuContext is not fully displayed in the drop-down menu in <View style={{flex Direction:'row',}>.

**Comment by honeyzhaoAliyun** [comment]
MenuContext is not fully displayed in the drop-down menu in <View style={{flex Direction:'row',}>.

**Comment by KrisLau** [comment]
Did you figure tout how to arrange this? It's not a problem with the library but I'm not sure how to get the menu above the parent view row
