### ISSUE TITLE
style prop for backdrop?

### ISSUE THREAD

**Issue by joncursi** [instea/react-native-popup-menu#14]
Would like to be able to customize the styles of the backdrop, i.e. backgroundColor and opacity.

**Comment by joncursi** [comment]
Sounds good!

Related to https://github.com/instea/react-native-popup-menu/issues/15 - it would be great if the backdrop were also animatable. Specifically supporting fade in and fade out.

**Comment by sodik82** [comment]
new properties added to allow styling of backdrop. animation will be covered in other issue.
