### ISSUE TITLE
The popup menu overlapped by other elements in Android

### ISSUE THREAD

**Issue by hkvega01** [instea/react-native-popup-menu#143]
The screenshot are as follow:

[https://i.postimg.cc/dQRNmw4Q/app.jpg]

Here is the partial code.

```
    render()
    {
        
        const BasicExample = () => (
                <MenuProvider style={styles.MenuContainer}>
                    <View>
                        <Menu>
                            <MenuTrigger>
                                <Icon
                                    name="menu"
                                    color='#fff'
                                    underlayColor={'#64b5f6'}
                                />
                            </MenuTrigger>

                            <MenuOptions optionsContainerStyle={{ marginLeft: -100, marginTop: 0 }}>
                                <MenuOption onSelect={() => alert(`Save`)} text="Save" />
                                <MenuOption onSelect={() => alert(`Delete`)}>
                                    <Text style={{ color: 'red' }}>Delete</Text>
                                      </MenuOption>
                                      <MenuOption
                                        onSelect={() => alert(`Not called`)}
                                        disabled={true}
                                        text="Disabled"
                                      />
                            </MenuOptions>

                        </Menu>
                    </View>
                </MenuProvider>
        );
        return(  
          <View style = {styles.MainContainer}>
            <View>
                <View>
                  <Header
                    outerContainerStyles={styles.topMenu}
                    centerComponent={{
                      text: 'Events',
                      style: { color: '#fff', fontWeight: 'bold', fontSize: 18 },
                    }}
                    rightComponent=
                        {BasicExample}
                    
                  />
                </View>
            </View>
```
If i don't use zIndex, the disabled option is under barcode layer, but even i use zIndex: 999 for MenuOptions tag, the popup menu is still unclickable, how to fix it?

**Comment by pegasus1982** [comment]
Please use MenuProvider in render, not in BasicExample
Like this
render()
    {
        
        const BasicExample = () => (
                    <View>
                        <Menu>
                            <MenuTrigger>
                                <Icon
                                    name="menu"
                                    color='#fff'
                                    underlayColor={'#64b5f6'}
                                />
                            </MenuTrigger>

                            <MenuOptions optionsContainerStyle={{ marginLeft: -100, marginTop: 0 }}>
                                <MenuOption onSelect={() => alert(`Save`)} text="Save" />
                                <MenuOption onSelect={() => alert(`Delete`)}>
                                    <Text style={{ color: 'red' }}>Delete</Text>
                                      </MenuOption>
                                      <MenuOption
                                        onSelect={() => alert(`Not called`)}
                                        disabled={true}
                                        text="Disabled"
                                      />
                            </MenuOptions>

                        </Menu>
                    </View>
        );
        return(  
          <MenuProvider style={styles.MenuContainer}>
          <View style = {styles.MainContainer}>
            <View>
                <View>
                  <Header
                    outerContainerStyles={styles.topMenu}
                    centerComponent={{
                      text: 'Events',
                      style: { color: '#fff', fontWeight: 'bold', fontSize: 18 },
                    }}
                    rightComponent=
                        {BasicExample}
                    
                  />
                </View>
            </View>
       ......
      </MenuProvider>

**Comment by hkvega01** [comment]
> Please use `MenuProvider` in return, not in` BasicExample`
> Like this
> 
> ```
> render()
>     {
>         
>         const BasicExample = () => (
>                     <View>
>                         <Menu>
>                             <MenuTrigger>
>                                 <Icon
>                                     name="menu"
>                                     color='#fff'
>                                     underlayColor={'#64b5f6'}
>                                 />
>                             </MenuTrigger>
> 
>                             <MenuOptions optionsContainerStyle={{ marginLeft: -100, marginTop: 0 }}>
>                                 <MenuOption onSelect={() => alert(`Save`)} text="Save" />
>                                 <MenuOption onSelect={() => alert(`Delete`)}>
>                                     <Text style={{ color: 'red' }}>Delete</Text>
>                                       </MenuOption>
>                                       <MenuOption
>                                         onSelect={() => alert(`Not called`)}
>                                         disabled={true}
>                                         text="Disabled"
>                                       />
>                             </MenuOptions>
> 
>                         </Menu>
>                     </View>
>         );
>         return(  
>           <MenuProvider style={styles.MenuContainer}>
>           <View style = {styles.MainContainer}>
>             <View>
>                 <View>
>                   <Header
>                     outerContainerStyles={styles.topMenu}
>                     centerComponent={{
>                       text: 'Events',
>                       style: { color: '#fff', fontWeight: 'bold', fontSize: 18 },
>                     }}
>                     rightComponent=
>                         {BasicExample}
>                     
>                   />
>                 </View>
>             </View>
>        ......
>       </MenuProvider>
> ```

hey, basicExample is just the variable name. I changed to use https://github.com/mxck/react-native-material-menu , it works perfectly
