### ISSUE TITLE
Popover "tail" doesn't appear 

### ISSUE THREAD

**Issue by connercms** [instea/react-native-popup-menu#148]
Using RN v0.57.1 and rnpm v0.14.2, I am unable to make the popup renderer "tail" appear, no matter what I configure with rendererProps. It simply appears as a box.

The following code taken directly from the example (with the exception of custom MenuTrigger child)

    <Menu renderer={renderers.Popover} rendererProps={{placement: 'bottom'}}>
        <MenuTrigger>
            <MaterialCommunityIcons name="filter" size={30} />
        </MenuTrigger>
        <MenuOptions>
            <MenuOption onSelect={() => alert(`Save`)} text="Save" />
            <MenuOption onSelect={() => alert(`Delete`)}>
              <Text style={{color: 'red'}}>Delete</Text>
            </MenuOption>
            <MenuOption onSelect={() => alert(`Not called`)} disabled={true} text="Disabled" />
        </MenuOptions>
    </Menu>

Produces the following

<img width="260" alt="screen shot 2019-02-21 at 11 31 49 am" src="https://user-images.githubusercontent.com/12799522/53189124-65db9280-35cc-11e9-9d61-59cb1993a7a7.png">

**Comment by connercms** [comment]
After looking through the library code, I discovered the default anchor style background color is set to white, so it won't show against white backgrounds. Might add this to the docs somewhere as it wasn't clear.

**Comment by connercms** [comment]
After looking through the library code, I discovered the default anchor style background color is set to white, so it won't show against white backgrounds. Might add this to the docs somewhere as it wasn't clear. For anyone with a similar issue, to configure the anchor colors, add anchorStyle inside the rendererProps 
```
<Menu renderer={renderers.Popover} 
rendererProps={{placement: 'bottom', anchorStyle: {backgroundColor: '#eaeaea'}}}>
```

**Comment by connercms** [comment]
After looking through the library code, I discovered the default anchor style background color is set to white, so it won't show against white backgrounds. Might add this to the docs somewhere as it wasn't clear. For anyone with a similar issue, to configure the anchor colors, add anchorStyle inside the rendererProps 
```
<Menu renderer={renderers.Popover} 
rendererProps={{placement: 'bottom', anchorStyle: {backgroundColor: '#eaeaea'}}}>
```

**Comment by IgorVanian** [comment]
@connercms So why the shadow isn't applied to the anchor? In the library the elevation is applied but not iOS shadow props.

**Comment by sodik82** [comment]
PR welcomed
