### ISSUE TITLE
Reverse animations needed for Menu disappearance

### ISSUE THREAD

**Issue by joncursi** [instea/react-native-popup-menu#15]
For the default renderer and slide renderer, the menu will scale / slide into place when the menu is opened. However, when the menu is closed, the menu will immediately disappear which causes a jarring flash and is not to spec with material design behavior / motion principles.

I'm thinking that these menus need reverse animations, i.e. they should animate out the exact reverse of how they animate in.

**Comment by sodik82** [comment]
as a part of this issue we might introduce a way how to animate backdrop as well ( see #14)

additional note: https://material.google.com/motion/duration-easing.html#duration-easing-speed
> Objects leaving the screen may have shorter durations, as they require less attention.

**Comment by joncursi** [comment]
Definitely on-board with the animations being shorter. I just think there needs to be some sort of slight motion on dismissal. You can see how material design animates menus out here:

https://material-design.storage.googleapis.com/publish/material_v_9/0B6Okdz75tqQsUWtQaDc0MnJOUmc/Components-Menus-Usage-Textfield_Dropdown_xhdpi_006.webm

I think a short fade + scale out would suffice for contextual menus, and a simple slide down for the bottom sheet menus.

**Comment by sodik82** [comment]
version `0.7` : menus are now closed with animation

**Comment by sodik82** [comment]
version `0.7.2`: backdrop is now also animated with fade in/out

**Comment by joncursi** [comment]
Did the backdrop animation out regress the slide out animation? I just upped to 0.7.2 and when I tap an item in the menu, everything flash disappears.

It does animate in though, it's just the out that I notice the flash.

**Comment by sodik82** [comment]
sorry - I don't clearly understand what do you mean (e.g. 'regress' or which 'flash' are you referring to :)) 

can you try our StylingExample if you can reproduce problem there?
can you give us more details - ios/android, which version have you used before or maybe some screenshot/video showing the problem?

**Comment by joncursi** [comment]
Hmm, I looked deeper into this today and can't reproduce my comment above. Happy to close, thank you for adding this!
