### ISSUE TITLE
!!!ASAP!!! 0.15.1 crash native apps!!!

### ISSUE THREAD

**Issue by oxyii** [instea/react-native-popup-menu#150]
[overflowY](https://github.com/instea/react-native-popup-menu/blob/master/build/rnpm.js#L1662) crash app just importing MenuProvider !!!

**Comment by jamesvweston** [comment]
Related to this issue: https://github.com/instea/react-native-popup-menu/pull/146

**Comment by jamesvweston** [comment]
For a temporary fix replace "^0.15.0" with "0.15.0" in package.json

**Comment by oxyii** [comment]
I know, thanks. Issue created for repo-members )

**Comment by sodik82** [comment]
Thanks for letting us know... Funny thing that `0.15.1` is working fine in expo ( https://snack.expo.io/@sodik82/react-native-popup-menu-with-trigger-long-press ) but `overflowY` seems not to be official property in RN. Fixed in `0.15.2`

**Comment by sodik82** [comment]
@oxyii is `0.15.2` fine?

**Comment by oxyii** [comment]
@sodik82 Yep, `0.15.2` works fine on native platforms. But have `useNativeDriver` warning on web when menu open

![_001](https://user-images.githubusercontent.com/39907210/53695217-8922f080-3dc9-11e9-845d-2ef83e864d98.png)

**Comment by oxyii** [comment]
@sodik82 I think in `build` folder must be 3 files
* index.js // <- just export from "react-native-popup-menu"
* react-native-popup-menu.js // <- for native platforms
* react-native-popup-menu.web.js // <- for web
or do not build at all.

Metro bundler will compile her-self.
Developers who works with web platform already made an ejection and added required `node_modules` libraries into babel config. Impossible to create a good RNWeb app without ejecting or using others libs for babel configuration like a [react-app-rewired](https://github.com/timarney/react-app-rewired) and [customize-cra](https://github.com/arackaf/customize-cra). IMHO )

**Comment by sodik82** [comment]
The build for RNWeb came from community. However I like your idea - two builds could use different env variables to enable/disable native driver. 

Could you create something like that? Or at least create new improvement issue :)

**Comment by oxyii** [comment]
Platform-specific code works fine natively. Just create *.<platform>.js )) I 

I don't have enough time to do that now but I just fixed web-warning. Look at PR
