### ISSUE TITLE
Popup menu not work with react-native-modal

### ISSUE THREAD

**Issue by huylv-teko** [instea/react-native-popup-menu#152]
Hi, when i put the menu trigger inside a Modal (from react-native-modal), the menu options always show behinds the modal. 
If i wrap the modal content with the `<MenuProvider>` (line 70 in image below), the modal won't show anymore.
![image](https://user-images.githubusercontent.com/47681966/54926803-a28c0800-4f43-11e9-9f14-07a6a5e91a08.png)

Here is the example in snack https://snack.expo.io/@huylv177/menupopup-modal

**Comment by sodik82** [comment]
Hi there,

I just moved `MenuProvider` to the "top" of the `Modal` and played a bit with styles and seems to work fine.

```
          <Modal
            onSwipeComplete={this.onClose}
            onBackdropPress={this.onClose}
            isVisible={this.state.modalVisible}
            style={styles.bottom}
            swipeDirection="down">
            <MenuProvider skipInstanceCheck style={styles.menuProvider}>
              <View style={{ backgroundColor: 'white' }}>
                {this.renderModalContent()}
              </View>
            </MenuProvider>
          </Modal>
```

Full example: https://snack.expo.io/@sodik82/menupopup-modal

**Comment by huylv-teko** [comment]
Yeah it works like a charm :D but why the menu provider make the children's style wrong. I think there are something wrong in MenuProvider. 
Btw do not remove the example above, i think many one maybe need too

**Comment by sodik82** [comment]
Menu provider has `flex:1` style to cover whole screen (e.g. in order to render backdrop) It looks like Modal has its own styles as well and you need to match them all together (e.g. I have removed styles from `styles.bottom` ).

**Comment by dmytro-kosiakov-brickred** [comment]
The solution with an explanation is here https://github.com/instea/react-native-popup-menu/issues/162#issuecomment-520983190
