### ISSUE TITLE
Option to use TouchableOpacity for MenuTrigger instead of TouchableHighlight?

### ISSUE THREAD

**Issue by joncursi** [instea/react-native-popup-menu#16]
Seems like the MenuTrigger is hard-coded to use TouchableHighlight. Would be great if the option was given to the developer / designer on which Touchable option to use, i.e. Highlight or Opacity. TouchableHighlight does not work for all use-cases, namely solo icons.

**Comment by joncursi** [comment]
Looks like this can be mitigated by using the context methods to open and close the menu from a completely custom element + handler, rather than using the built-in behavior of `MenuTrigger` component.

**Comment by sodik82** [comment]
reopening as I like the idea :)
