### ISSUE TITLE
Popup menu not showing over Modal component

### ISSUE THREAD

**Issue by AstrisDev** [instea/react-native-popup-menu#162]
I'm trying to use component in Modal window (showing post) as context menu.
When I press trigger menu renders under Modal.
Any ideas how to fix that?

**Comment by sodik82** [comment]
https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#menuprovider

>  Note: It is important that <MenuProvider /> is on the top of the component hierarchy (e.g. ScrollView should be inside of MenuProvider) and wraps all <Menu /> components. This is needed in order to solve z-index issues. The only known exception is when you use Modal - you need to place (additional) 'MenuProvider' inside of 'Modal' (see our ModalExample)
