### ISSUE TITLE
How to dismiss the menu after opening without select any MenuOption??

### ISSUE THREAD

**Issue by prabaltiwari09** [instea/react-native-popup-menu#164]
I added the Menu in the header so that on the right side so that I can use the menu in header. Now when I open the menu and select any option it works fine. But when I want to dismiss the menu without selecting any option there is no such option.

I also want to style the text which I am showing in the header but unable to do so. Here are the screenshots.
![Screenshot_2019-10-04-14-29-18-747_host exp exponent 1](https://user-images.githubusercontent.com/23833063/66195071-78b25b80-e6b3-11e9-8951-099ff2e9014c.png)
![Screenshot_2019-10-04-14-28-55-847_host exp exponent 1](https://user-images.githubusercontent.com/23833063/66195128-98e21a80-e6b3-11e9-99f1-1927b4742e25.png)

**Comment by prabaltiwari09** [comment]
If I open the menu then without selecting any option it is not getting closed.

**Comment by sodik82** [comment]
user can close the menu by clicking anyway outside. if it is not working, you probably haven't place your MenuProvider on the top of your application as described in documentation.

**Comment by jerryheir** [comment]
how can someone dynamically open and close a menu. I cant find that in the docs

**Comment by sodik82** [comment]
there are multiple ways:
1. declarative: https://github.com/instea/react-native-popup-menu/blob/master/doc/examples.md#declarative-menu

2. imperative: 
a) via provider: https://github.com/instea/react-native-popup-menu/blob/master/doc/examples.md#declarative-menu
b) directly via menu instance: https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#methods
