### ISSUE TITLE
rendererProps doesn't work 

### ISSUE THREAD

**Issue by Karpengold** [instea/react-native-popup-menu#167]
I'm trying to pass style properties to ContextMenu component but it doesn't work: 

```    
    
<Menu renderer={renderers.ContextMenu}  rendererProps={{style: {marginLeft: 20}}}>
           <MenuTrigger>
                        {Item}
            </MenuTrigger>
             <MenuOptions>
                    <NavigationList type='popup' items={data} />
              </MenuOptions>
</Menu >
```

I logged style object in render method of ContextMenu component and got this: 

```
console.log(style)
// result: [undefined, undefined]
```

**Comment by sodik82** [comment]
not sure, but styling is not done via `rendererProps`.... check our styling example. `rendererProps` is escape hatch for "other" props that are not controlled via other (more semantic props).

**Comment by Karpengold** [comment]
@sodik82 Yes, I checked styling example, but I didn't find example how to control position of ContextMenu element, i.e. add margin. So I tried to do it via rendererProps but also didn't come to success

**Comment by sodik82** [comment]
something like https://stackoverflow.com/questions/58435267/how-to-add-offset-to-the-popup-menu or https://stackoverflow.com/questions/45577484/react-native-popup-menu-moving-the-options-box ?

I know it is a bit tricky because there is no single style that controls how popup menu looks

**Comment by Karpengold** [comment]
@sodik82 thanks, that's exactly what I need
