### ISSUE TITLE
Not triggering MenuOption select when wrapped in a scrollView

### ISSUE THREAD

**Issue by anooppoommen** [instea/react-native-popup-menu#168]
I made a custom renderer for the component and instead of wrapping it in a View I did it in a ScrollView everything renders just fine but when I go to press the menu option it does not trigger the onSelect function. Instead just closes the menu. But on doing a double-tap it works fine.

(I've set a fixed height for the options container that's why I needed it to be wrapped in a scroll view)

// Cutom renderer
`
<ScrollView {...other} style={[styles.options, style]} nestedScrollEnabled={true} accessible={true}>
          {children}
</ScrollView>
`

//Component.tsx

`<Menu
            ref={this.setRef.bind(this)}
            renderer={Popover}
            rendererProps={{placement: 'bottom', anchorStyle: styles.anchor}}>
            <MenuTrigger text={''} />
            <MenuOptions
              customStyles={{
                optionsContainer: [styles.cust, {width: this.state.width}],
                optionText: [commonStyles.textPoppins, styles.optionText],
              }}>
              {options}
            </MenuOptions>
          </Menu>`

**Comment by sodik82** [comment]
Hi there,

if you just need scrollview, you don't need customer renderer - see https://github.com/instea/react-native-popup-menu/blob/master/doc/examples.md#menu-within-scroll-view

The thing with `onSelect` is strange - have it worked without your new renderer?
