### ISSUE TITLE
How do I style the container(dialog) of the menu?

### ISSUE THREAD

**Issue by diamantisufi** [instea/react-native-popup-menu#178]

**Comment by sodik82** [comment]
something like https://github.com/instea/react-native-popup-menu/blob/master/doc/examples.md#styled-menu ?

**Comment by diamantisufi** [comment]
@sodik82  as I can see in this example, the Trigger is being styled, I want to style the container after being triggered, so after it opens. Been trying to style the MenuOptions but there is a parent to that which I cannot style.

**Comment by sodik82** [comment]
what is container for you? 

for me the container is green (in our example). do you mean backdrop (see https://github.com/instea/react-native-popup-menu/blob/master/examples/StylingExample.js )?

**Comment by diamantisufi** [comment]
This is what I want to style, I tried giving styles to the <MenuOptions> but there is a parent to MenuOptions.

![Picure](https://user-images.githubusercontent.com/28764471/75681496-ffd02380-5c93-11ea-8018-ee1add72d662.PNG)

**Comment by diamantisufi** [comment]
Found it. It's the optionsContainer! Thank you
