### ISSUE TITLE
The popup Is shown behind the other items in the page

### ISSUE THREAD

**Issue by dor6** [instea/react-native-popup-menu#180]
The popup Is shown behind the other items in the page, I open it inside a modal with menuProvider inside the modal, the popup menu is shown behind the other elements in the page.

**Comment by dibyopra** [comment]
i have the same issues when I use react-native-modal

**Comment by aliwaqar9811** [comment]
Making MenuProvider as children of Modal resolve the issue. but the onBackdropPress of modal isn't working.

**Comment by jaymes-bearden** [comment]
I had the same issue -- in my case I had a react-native-modal and the popup menu was behind the modal. I my case, I had to add `<MenuProvider skipInstanceCheck>` as a child of `<Modal>`. 

See: https://github.com/instea/react-native-popup-menu/blob/master/examples/ModalExample.js and https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#menuprovider specifically:

> The only known exception is when you use Modal - you need to place (additional) 'MenuProvider' inside of 'Modal' (see our ModalExample) Note: MenuProvider was formerly named MenuContext which is now deprecated.

**Comment by saidev** [comment]
@jaymes-bearden 
Thank you, I just raw into this issue and your comment helped fixed it.  Is this still considered a bug, should we close this thread?  Seem more like a feature if skipInstanceCheck exists as a parameter.

**Comment by sodik82** [comment]
as @jaymes-bearden pointed out, it is really a feature (due to the nature of modals). and it is also documented => I will close this issue.

**Comment by goswamikaushik001** [comment]
this able fix issue of popup is not show , it is behind the modal , but now my manuoptions are behind the items that in the modal
