### ISSUE TITLE
how to disable backdrop.

### ISSUE THREAD

**Issue by beingArkReal** [instea/react-native-popup-menu#181]
I'm looking for how to disable backdrop property where we can click the other components even though it's open.

**Comment by sodik82** [comment]
currently it is not possible and the popup menu is designed that way, you can open only one menu at a time (or at least one per provider...).

you can't disable backdrop but maybe you can style it "out" somehow.

**Comment by garyzhu2** [comment]
hi are there any hints as to how i can "style" it out? I've read on previous threads how we will have to double click to close then open another menu, but I really want to be able to open other menus with one click. Thanks
