### ISSUE TITLE
withMenuContext is not declared in index.d.ts

### ISSUE THREAD

**Issue by nitzanbueno** [instea/react-native-popup-menu#182]
I'm on version 0.15.7 and the function withMenuContext works fine, but is not declared in index.d.ts, and thus causes a compilation error when imported.

**Comment by sodik82** [comment]
hi there, are you willing to contribute the fix?

**Comment by nitzanbueno** [comment]
I'll try my best.

**Comment by nitzanbueno** [comment]
I wasn't sure if I should add types for the MenuRegistry object, so I did.
If you need me to, I can remove them

**Comment by nitzanbueno** [comment]
Could you merge the PR?

**Comment by sodik82** [comment]
thanks for your help, merged
