### ISSUE TITLE
Custom renderers throw an error when using arrow functions

### ISSUE THREAD

**Issue by mbrimmer83** [instea/react-native-popup-menu#183]
When implementing a custom renderer that is an arrow function, an error is thrown `isFunctional` Uncaught TypeError: Cannot read property 'render' of undefined. This appears to be do to the prototype being undefined on an arrow function.

https://github.com/instea/react-native-popup-menu/blob/master/src/MenuProvider.js#L17

**Comment by madox2** [comment]
Thanks for reporting! You are right, arrow functions do not have prototype, `isFunctional` function needs to be fixed.

**Comment by sodik82** [comment]
can you try `0.15.8`?
