### ISSUE TITLE
React.native-popup-menu not work in expo SDK 37

### ISSUE THREAD

**Issue by joselokus** [instea/react-native-popup-menu#184]
I have updated to SDK 37 and I have lost all the design on the tablet.

I suppose it is due to the react-native-popup-menu library, because I only use it on a tablet, not on mobile, and it works perfectly for me on mobile.

It may be because Expo deprecated UIWebView?

Thanks

**Comment by sodik82** [comment]
popup menu implements only "pure" ReactNative, i.e. nothing with web view. can you check more deeply?
