### ISSUE TITLE
Submenus support?

### ISSUE THREAD

**Issue by liqiangsu** [instea/react-native-popup-menu#185]
Is submenu supported?
If not, it would be great to have.

**Comment by sodik82** [comment]
hi there, submenus are not supported out of the box. 

if you like, you can render anything in the menu, so you can do it yourself (maybe just change the menu options on 1st level option click, or implement kind of accordion).

**Comment by liqiangsu** [comment]
> maybe just change the menu options on 1st level option click

I tried that, does not seem to work.  The 2nd level menu wont dispay.
I go with grouping instead

**Comment by sodik82** [comment]
you can't open two different menus at one time (design constraint), thus options is grouping (accordion) or change/replace the options on click should be possible (although might not be optimal).
