### ISSUE TITLE
Menu showing on the Bottom Bar

### ISSUE THREAD

**Issue by janardhanmupparaju** [instea/react-native-popup-menu#194]
I am trying to show the popup menu on the list item but when I click on last to the second item it was showing the popup menu, but on the bottom bar. like the below screen.
![Simulator Screen Shot - iPhone 11 - 2020-10-02 at 09 25 24](https://user-images.githubusercontent.com/16552148/94946702-6408cf00-0491-11eb-9b84-fcf0c0c3cbf2.png)

I am using this one also
rendererProps={{ preferredPlacement: 'top' }}

**Comment by janardhanmupparaju** [comment]
> I am trying to show the popup menu on the list item but when I click on last to the second item it was showing the popup menu, but on the bottom bar. like the below screen.
> ![Simulator Screen Shot - iPhone 11 - 2020-10-02 at 09 25 24](https://user-images.githubusercontent.com/16552148/94946702-6408cf00-0491-11eb-9b84-fcf0c0c3cbf2.png)
> 
> Except that one, for every list item popup menu working good like the below screens.
> 
> for click on the first item menu
> ![Simulator Screen Shot -1 - iPhone 11 - 2020-10-02 at 09 31 41](https://user-images.githubusercontent.com/16552148/94947361-61f34000-0492-11eb-93c6-9903a35eb91f.png)
> 
> for click on the 2nd item
> ![Simulator Screen Shot-2 - iPhone 11 - 2020-10-02 at 09 32 03](https://user-images.githubusercontent.com/16552148/94947415-78010080-0492-11eb-9321-db06dfd47312.png)
> 
> for click on the 3rd item
> ![Simulator Screen Shot-3 - iPhone 11 - 2020-10-02 at 09 32 20](https://user-images.githubusercontent.com/16552148/94947465-89e2a380-0492-11eb-93d0-3897e5b5ac25.png)
> 
> for click on 4th item
> ![Simulator Screen Shot - iPhone 11 - 2020-10-02 at 09 25 24](https://user-images.githubusercontent.com/16552148/94947501-9bc44680-0492-11eb-961d-923b1c8b0ed2.png)
> 
> for click on 5th item
> ![Simulator Screen Shot-5 - iPhone 11 - 2020-10-02 at 09 32 47](https://user-images.githubusercontent.com/16552148/94947551-a8e13580-0492-11eb-832a-9d8b57dd8fd8.png)

**Comment by sodik82** [comment]
popup menu will use any place on the screen.... so I would say it is "expected" behaviour. I see two options:

1. let your MenuProvider span only the space you want to use (i.e. the inner content) although it is not officially recommended.
2. you can play with https://github.com/instea/react-native-popup-menu/blob/master/doc/extensions.md - compute the position of the popup menu by our self (or maybe just adjust the default computation) so that it does not use bottom of your screen.
