### ISSUE TITLE
e2e testing using testID and customStyles

### ISSUE THREAD

**Issue by mikbry** [instea/react-native-popup-menu#197]
This component is not designed for e2e testing, see #155.
But i found a workaround using customStyles. In fact customStyles are more customProps for sub-components.
For MenuTrigger:
```
<MenuTrigger customStyles={{ triggerTouchable: { testID: 'menu-trigger' } }} />
```
For MenuOption:
```
<MenuOption customStyles={{ optionTouchable: { testID: 'option-1' } }} />
```
Tested using Detox on Android emulator

**Comment by sjmdocto** [comment]
This works for MenuTrigger, but no testID is showing up for MenuOption for me.

**Comment by mikbry** [comment]
For me it is working ok testing 4/5 different MenuOptions. And I checked back at MenuOptions source code:
```
<Touchable
          onPress={() => this._onSelect()}
          {...defaultTouchableProps}
          {...customStyles.optionTouchable}
        >
          {rendered}
</Touchable>
```
So `optionTouchable` is the right parameter. Are you testing on iOS or React Web, if so Touchable is a different component `TouchableHighlight`, I didn't test. Also if MenuOption is disable, the parameter can't be changed to optionWrapper as it is using style instead if props.

**Comment by sodik82** [comment]
> This component is not designed for e2e testing, see #155.

PRs are welcomed :) supporting `testID` makes sense to me

**Comment by mikbry** [comment]
I work on the e2e PR ;-)
Regarding customStyles not implemented in Touchable as style={customStyles.xxxTouchable} but directly as props is it a bug or ?

**Comment by sodik82** [comment]
thanks @mikbry for PR.

Regarding the question (if I get it right), spreading `optionTouchable` directly (without `style=`) was intention so that you can change non-style properties like e.g. `underlayColor` (see [api](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#custom-styles-2) ). You can always use `optionTouchable={style: {....}} to set the styles.

**Comment by sodik82** [comment]
well... most of those are styles, but this is "exception" as you need props
to style touchable....

**Comment by sodik82** [comment]
but yes, it is suboptimal name.

**Comment by sjmdocto** [comment]
> For me it is working ok testing 4/5 different MenuOptions. And I checked back at MenuOptions source code:
> 
> ```
> <Touchable
>           onPress={() => this._onSelect()}
>           {...defaultTouchableProps}
>           {...customStyles.optionTouchable}
>         >
>           {rendered}
> </Touchable>
> ```
> 
> So `optionTouchable` is the right parameter. Are you testing on iOS or React Web, if so Touchable is a different component `TouchableHighlight`, I didn't test. Also if MenuOption is disable, the parameter can't be changed to optionWrapper as it is using style instead if props.

I'm using Jest to run tests. I'm trying to use React Native Testing Library such that I can find a MenuOption by it's testID,  click on that option, and then test my own code. But fireEvent.press() isn't finding the MenuOption's testID. And when I use Jest's snapshot feature, I can find the testID of MenuTrigger, but I can't find any MenuOption's testID's.

I copied the code that you wrote:
**<MenuOption customStyles={{ optionTouchable: { testID: 'option-1' } }} />**

**Comment by mikbry** [comment]
@sjmdocto  you should test latest version 0.15.10. I added support for testID in MenuOption and MenuTrigger

**Comment by CallumHemsley** [comment]
> > For me it is working ok testing 4/5 different MenuOptions. And I checked back at MenuOptions source code:
> > ```
> > <Touchable
> >           onPress={() => this._onSelect()}
> >           {...defaultTouchableProps}
> >           {...customStyles.optionTouchable}
> >         >
> >           {rendered}
> > </Touchable>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So `optionTouchable` is the right parameter. Are you testing on iOS or React Web, if so Touchable is a different component `TouchableHighlight`, I didn't test. Also if MenuOption is disable, the parameter can't be changed to optionWrapper as it is using style instead if props.
> 
> The popup menu works fine on iOS/Android simulators, but I'm trying to use Jest to run tests. I'm trying to use React Native Testing Library such that I can find a MenuOption by it's testID, click on that option, and then test my own code. But fireEvent.press() isn't finding the MenuOption's testID. And when I use Jest's snapshot feature, I can find the testID of MenuTrigger, but I can't find any MenuOption's testID's.
> 
> I copied the code that you wrote: **<MenuOption customStyles={{ optionTouchable: { testID: 'option-1' } }} />**

Hey @sjmdocto did you find a solution for this? Exact same use case.

Should also be noted I'm on version 0.15.12 @mikbry - looks like `fireEvent.press` is causing the menu options to show in the DOM.

**Comment by plambir93kek** [comment]
No `MenuOption` in snapshots, also no elements found by testID of menu option.
```
const menuOptionStyle = useMemo(
    (): MenuOptionCustomStyle => ({
      optionWrapper: {
        ...style.option,
        ...optionStyle
      },
      OptionTouchableComponent: TouchableOpacity,
      optionTouchable: { testID: 'dropdown-option' }
    }),
    [optionStyle]
  );

  return (
    <MenuOption
      customStyles={menuOptionStyle}
      disabled={isDisabled}
      value={value}
      onSelect={handleSelect}>
      {icon && <View style={[style.icon, iconStyle]}>{icon}</View>}
      <AppText style={titleStyle}>{title}</AppText>
    </MenuOption>
  );
```

**Comment by shail-spreadd** [comment]
still not working for me using RNTL fireevent.press is not opening my menu @sodik82

**Comment by personalizedrefrigerator** [comment]
I've had success with mocking both `View.measure` and `View.onLayout`:
```ts
import type * as ReactNative from 'react-native';

// Mock react-native to modify View's constructor.
jest.mock('react-native', () => {
	// See https://jestjs.io/docs/jest-object#jestrequireactualmodulename
	const reactNative = jest.requireActual<typeof ReactNative>('react-native');
	const ViewMock = class extends reactNative.View {
		public constructor(props: ReactNative.ViewProps) {
			super(props);

			// react-native-popup-menu won't show menus until an onLayout event is fired on
			// a View just within its MenuProvider.
			// To work around this, call onLayout for all View components.
			if (this.props.onLayout) {
				this.props.onLayout({ nativeEvent: { layout: { x: 0, y: 0, width: 100, height: 100 } }} as any);
			}
		}

		// The layout for a MenuTrigger is found using .measure. Mock .measure to allow
		// triggers to display menus:
		public mesaure = (callback: ReactNative.MeasureOnSuccessCallback) => {
			callback(0, 0, 150, 150, 0, 0);
		};
	};

	// Use a Proxy object, rather than {...reactNative, View: ViewMock}. React Native warns
	// when attempting to access certain deprecated properties (which is done by ...reactNative).
	return new Proxy(reactNative, {
		get(target, property) {
			if (property === 'View') {
				return ViewMock;
			}
			return target[property as keyof typeof ReactNative];
		},
	});
});
```
