### ISSUE TITLE
MenuTrigger is not properly styleable because of outer View

### ISSUE THREAD

**Issue by mschipperheyn** [instea/react-native-popup-menu#20]
MenuTrigger has an outer view but the style is passed to the inner view. This makes the trigger not properly styleable, e.g. using flex properties on the box.

**Comment by madox2** [comment]
Thanks for reporting! We should definitely provide a way how to style outer view too. E.g. using `customStyles`

**Comment by sodik82** [comment]
thank you, with `0.7.1` it is now possible. check our [StyllingExample](https://github.com/instea/react-native-popup-menu/blob/master/examples/StylingExample.js)
