### ISSUE TITLE
how do I changed the underlayColor on menu trigger? it doesn't seem to work 

### ISSUE THREAD

**Issue by astroana** [instea/react-native-popup-menu#204]
<Menu>
        <MenuTrigger
            customStyles={{
              TriggerTouchableComponent: TouchableHighlight,
              triggerTouchable: {
                activeOpacity: 0.5,
                underlayColor: 'green',
              },
            }}
          >
         <FontAwesome5I
              style={navstyle.notificationicon}
              name="bell"
              solid
            />
          </MenuTrigger>

          <MenuOptions>
            <MenuOption>
              <Text>
                Sample
              </Text>
            </MenuOption>
          </MenuOptions>
        </Menu>

underlay color doesn't change when clicked it stays the same color

![menu](https://user-images.githubusercontent.com/48448899/107492801-ce601780-6bc7-11eb-87ca-98d30df814a2.jpg)

**Comment by astroana** [comment]
got it working

**Comment by nsdub** [comment]
In case you were like me and wondering why setting the underlayColor doesn't work on Android, the culprit lies [here](https://github.com/instea/react-native-popup-menu/blob/5e545c808c9c9aa05a6ed9478f79f48a7fef8e8f/src/helpers.js#L30). 

```
export function makeTouchable(TouchableComponent) {
  const Touchable = TouchableComponent || Platform.select({
    android: TouchableNativeFeedback,
    ios: TouchableHighlight,
    default: TouchableHighlight,
  });
  let defaultTouchableProps = {};
  if (Touchable === TouchableHighlight) {
    defaultTouchableProps = { underlayColor: 'rgba(0, 0, 0, 0.1)' };
  }
  return { Touchable, defaultTouchableProps };
}
```
If you switch android to the `TouchableHighlight` component as well, then you'll be set.
