### ISSUE TITLE
Not able to use icon in place of text in MenuTrigger

### ISSUE THREAD

**Issue by Lekhrajk** [instea/react-native-popup-menu#210]
I want to use Icon in place of Text for triggering the menu but I didn't find a way to use it !.
Is there any way to use icons/image in place of normal text

**Comment by kfiggins** [comment]
Hey @Lekhrajk 

I'm guessing you are using the "text" property on the MenuTrigger. Try passing your icon in as a child to the MenuTrigger component. See below for a simple example.

`<MenuTrigger>                    
       <FontAwesome name={"filter"}  />
   </MenuTrigger>`

**Comment by sodik82** [comment]
should work.... https://stackoverflow.com/questions/44990755/how-to-set-an-icon-in-menutrigger
