### ISSUE TITLE
How do you keep the menu open when tapping a MenuOption?

### ISSUE THREAD

**Issue by GollyJer** [instea/react-native-popup-menu#211]
It seems from the documentation that returning `false` should keep the menu open, but I'm missing something simple.

Here's what I tried.
```javascript 
onSelect={() => {
   toggleIsWalletSelected(wallet);
   return true;
}}
```
But the menu still closes.

Thanks for any pointers!

**Comment by sodik82** [comment]
here is working example https://github.com/instea/react-native-popup-menu/blob/5e545c808c9c9aa05a6ed9478f79f48a7fef8e8f/examples/Example.js#L25
