### ISSUE TITLE
How to close menu?

### ISSUE THREAD

**Issue by bexoss** [instea/react-native-popup-menu#24]
Hello, Thanks to open this project.

I'm using your react-native-popup-menu for logout button. 
when button clicked the authentication deleted and screen will go to login . 
but the menu still left. 

How to close this menu when screen switched?

```javascript
 <Menu>
                        <MenuTrigger>
                            <Icon
                                name='more-vert'
                                color='#fff'
                            />
                            </MenuTrigger>
                        <MenuOptions>
                            <MenuOption value={1}>
                                <Text onPress={ () => {
                                this.props.onLogout()
                               
                                } }>logout</Text>
                            </MenuOption>
                        </MenuOptions>
                    </Menu>

```

**Comment by madox2** [comment]
Hi, you are handling logout event in `Text` component and therefore handlers to close menu are not trigerred. Try to pass it to the `onSelect` handler of `MenuOption`:

```javascript
<MenuOption onSelect={() => this.props.onLogout()}>
  <Text>logout</Text>
</MenuOption>
```

**Comment by bexoss** [comment]
@madox2 Bravo! Thanks!!

**Comment by sodik82** [comment]
more possibilities you can find on this migrated [SO question](http://stackoverflow.com/questions/42780996/how-to-close-react-native-popup-menu)
