### ISSUE TITLE
Controlled menu does not animate during closing

### ISSUE THREAD

**Issue by sodik82** [instea/react-native-popup-menu#25]
It seems that controlled menu does not animate when closed via props.

Expected: it should animate same as uncontrolled menu.

version: 0.7.2
platforms: both

**Comment by rsonnyprakoso** [comment]
@sodik82 I solve this issue by putting close menu action (i.e. setting local state to false) in timeout (around 200ms).

Probably this logic could be added to the menu component as well?

**Comment by sodik82** [comment]
thanks for workaround - right now I still believe it can be fixed properly :) but I need to look little bit deeper.

**Comment by sodik82** [comment]
should be fixed in `0.7.4`
