### ISSUE TITLE
Did the full description of API disappear?

### ISSUE THREAD

**Issue by marvanov** [instea/react-native-popup-menu#252]
I had tabs open in my browser with the description of API, but now they show 404.
I remember that there was an opportunity to reorient the display direction of the popover.
Please return the full API or show me, **thanks**!
And i would like to know if i can recolor the triangle pointing to the trigger

**Comment by sodik82** [comment]
sorry... our bad - some migration scripts were wrong... should be ok now.

**Comment by marvanov** [comment]
ok, thanks!
