### ISSUE TITLE
MenuOption testID type error

### ISSUE THREAD

**Issue by Elolawyn** [instea/react-native-popup-menu#274]
The prop `testID` was added to [`MenuOption` component](https://github.com/instea/react-native-popup-menu/blob/master/src/MenuOption.js) but in file [`index.d.ts`](https://github.com/instea/react-native-popup-menu/blob/master/src/index.d.ts) the prop `testID` was added to [`MenuOptions`](https://github.com/instea/react-native-popup-menu/blob/master/src/MenuOptions.js) (which do not have the prop `testID`).

**Comment by sodik82** [comment]
thanks, would you (or someone else) be willing to make PR?
