### ISSUE TITLE
🐞 Subtitle not showing on the Menu items

### ISSUE THREAD

**Issue by imransilvake** [instea/react-native-popup-menu#275]
Problem:
The subtitle on iOS is not working. It doesn't do anything when I add the subtitle.
<img width="482" alt="Screenshot 2023-06-13 at 23 23 59" src="https://github.com/instea/react-native-popup-menu/assets/13087225/56844843-6b42-454d-9da0-53db2c933281">
<img width="251" alt="Screenshot 2023-06-13 at 23 24 23" src="https://github.com/instea/react-native-popup-menu/assets/13087225/b3546abe-9819-4f57-8471-653086fd21c5">

Platform: iOS
Versions:
```
"@react-native-menu/menu": "^0.8.0",
"react-native": "0.71.8",
"react": "18.2.0",
```

**Comment by sodik82** [comment]
we are not "@react-native-menu/menu"
