### ISSUE TITLE
In the renderer, pass the close function to which component through props to execute the exit animation

### ISSUE THREAD

**Issue by Stephen-Song** [instea/react-native-popup-menu#278]
![image](https://github.com/instea/react-native-popup-menu/assets/58379214/19ddb5b9-a40a-467e-b9f8-c6b6d780380e)

I implemented the close function, but I don't know where to execute this asynchronous function or pass it to which component，Can anyone help me 🙏

**Comment by sodik82** [comment]
"easiest" way is to implement renderer as class component - see eg. https://github.com/instea/react-native-popup-menu/blob/ca2e3088ee39aeebd03c40f4d5ff3d1ac94f1e90/src/renderers/SlideInMenu.js

same could be done also with hooks - https://react.dev/reference/react/useImperativeHandle#exposing-your-own-imperative-methods
