### ISSUE TITLE
popup slide in not open when rotate screen

### ISSUE THREAD

**Issue by Deboracgs** [instea/react-native-popup-menu#29]
When rotate the screen android, the popup not open, how resolve this?

**Comment by sodik82** [comment]
hi, just for information - which version of RN do you use?

**Comment by Deboracgs** [comment]
react-native-cli: 2.0.1
react-native: 0.41.2

**Comment by sodik82** [comment]
I have tried our [example](https://github.com/instea/react-native-popup-menu/blob/master/examples/Example.js) and it is working on both ios and android - although it is different version of RN.

can you verify it? thanks

**Comment by sodik82** [comment]
closing due - will reopen with new information.
