### ISSUE TITLE
undefined is not an object (this.context.menuActions._notify)

### ISSUE THREAD

**Issue by johnmurphy01** [instea/react-native-popup-menu#3]
This is my render code for a menu within my application:
 ```
<View style={{ alignItems: 'flex-end', flex: 1, justifyContent: "center" }}>

            <Menu onSelect={this.handleMenuSelection.bind(this) }>
                <MenuTrigger>
                    <View ref="menuButton"  style={{ padding: 10, paddingRight: 15 }}>
                        <Icon name="bars" style={{ color: "white" }} size={20} />
                    </View>
                </MenuTrigger>
                <MenuOptions>
                    <MenuOption value={0}>
                        <Text>Settings</Text>
                    </MenuOption>
                    <MenuOption value={1}>
                        <Text>Send Feedback</Text>
                    </MenuOption>
                </MenuOptions>

            </Menu>

        </View>
```

This code worked before I migrated to React Native 0.26 and when I was using the react-native-menu component. After upgrading to RN 0.26, react-native-menu no longer works due to an issue with shape. It was suggested to move to react-native-popup-menu. However, now the app crashes with the following error: undefined is not an object(this.context.menuActions._notify). 

Any help would be greatly appreciated.

Thanks

**Comment by johnmurphy01** [comment]
I figured it out. I had to have a MenuContext surrounding the Menu before it would work. This previously worked with react-native-menu but does not with react-native-popup-menu.

**Comment by sodik82** [comment]
thanks for reporting (and figuring the problem)

so you had no MenuContext at all? We haven't known that previous lib was working without MenuContext (they are mentioning in their docu _You need to place a MenuContext somewhere in your application, usually at the root.  Menus will open within the context ..._)

or you just placed your menu outside the menu context? I guess that we will make at least better error in this situation. Or do you think it is common pattern to use `Menu` outside `MenuContext`?

**Comment by johnmurphy01** [comment]
No, I think MenuContext is fine as a wrapper for Menu. It's possible that we had it in the root as you specified. I may have removed the MenuContext due to another un-related issue. In any case, it seems to be working now, and I appreciate your response.
