### ISSUE TITLE
Popup menu does not show on React Native Modal

### ISSUE THREAD

**Issue by Wasylmakarenko** [instea/react-native-popup-menu#30]
Hi

You've made great thing.

However, let me issue one bug on my implementation.

I've tried to show open popup on standard Modal of react-native but it laid under modal.
Please see screenshot.

![image](https://cloud.githubusercontent.com/assets/22398446/25529972/11ee33e4-2c2d-11e7-8c97-0cbbf5924af1.png)

"react-native": "0.36.0-rc.1"
"react-native-popup-menu": "^0.7.3"

Platform: iOS(iPad Air)

Hope your quick support

Thanks
Best regards

**Comment by sodik82** [comment]
for future possible visitors - popup menu inside a modal needs little bit extra settings - as [documented](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#menucontext) and also available between [examples](https://github.com/instea/react-native-popup-menu/blob/master/examples/ModalExample.js).
