### ISSUE TITLE
MenuOption with custom icons.

### ISSUE THREAD

**Issue by nataroo** [instea/react-native-popup-menu#33]
I asked this question in stackoverflow
https://stackoverflow.com/questions/44079480/how-to-include-menu-options-with-custom-icons

I want to include menu options with custom icons.  Your documentation gives an example with a checkmark but I want more custom icons.  What is the best way to go about it?  Based on the answer in stackoverflow, I tried the following:

```
const IconOption = (props) => (
  <MenuOption {...props}>
     <Icon color={ICON_COLOR} name={props.iconName} size={ICON_SIZE} />
     {props.children}
  </MenuOption>
);

<MenuOptions customStyles={MenuOptionStyles}>
    <IconOption
        iconName='md-bookmark'
        onSelect={this.onSelectSave.bind(this)}
        text={MenuOptionStrings.Save}
    />
</MenuOptions>
```

But I still see only text in my menu options, don't see the icon.  I also tried getting the unicode values for the icons that I need and setting the same way as the CheckedOption in your examples, but the icons don't render, maybe it is some font issue?

**Comment by sodik82** [comment]
The problem with your code is mixing of `text` and `children` properties. See updated [ExtensionExample.js](https://github.com/instea/react-native-popup-menu/blob/master/examples/ExtensionExample.js#L16) for working example.

**Comment by nataroo** [comment]
Thanks, that worked.

**Comment by roadev** [comment]
And what about of using an icon as a menu trigger?

https://stackoverflow.com/questions/44990755/how-to-set-an-icon-in-menutrigger

**Comment by nataroo** [comment]
The given example works well on iOS but the icons/images are not being displayed well on Android.  I see really tiny images on Android.  This is the code:
`const IconOption = ({iconName, text, ...others}) => (
    <MenuOption {...others} >
        <Text>
            <Image source={iconName} />
            {'   ' + text}
        </Text>
    </MenuOption>
`);
`<IconOption
         iconName={require('../../assets/example.png')}
         onSelect={this.onExample.bind(this)}
         text={Strings.Example}
 />`

**Comment by sodik82** [comment]
have you tried to set the image size explicitly?

**Comment by nataroo** [comment]
Yes I have and that doesn't work either.

**Comment by sodik82** [comment]
Quite funny - must be some RN android quirk.
It works if you put image outside of the text component - see expo example: https://snack.expo.io/H1XAXn7wW

```
        <MenuOption value={2}>
          <View style={{flexDirection:'row'}}>
            <Image style={{width: 50, height: 50}}
              source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}} />
            <Text style={{color: 'red'}}> Two</Text>
          </View>
        </MenuOption>
```

**Comment by tasawar-hussain** [comment]
@sodik82 the above example does not really work. Can you confirm it?. I am using the latest version of library with react-native-web and Image is not displayed, only text is displayed. may the behavior has been changed. How can i display an image along with text in menu options?

Thanks

**Comment by sodik82** [comment]
I am not aware of any significant change on our side. Everything you render inside MenuOption should be there unless you use `text` prop. Can you check it more deeply?
