### ISSUE TITLE
How to set a Component for MenuTigger ?

### ISSUE THREAD

**Issue by CusProjects** [instea/react-native-popup-menu#38]

**Comment by madox2** [comment]
Hi, what exactly do you want to set? To show custom component in `MenuTrigger` you can simply pass it down to the children, for example:
```javascript
<MenuTrigger>
  <MyCustomComponent />
</MenuTrigger>
```
If you want to use different `Touchable` component you can use `customStyles` prop. Here is [the example](https://github.com/instea/react-native-popup-menu/blob/master/examples/TouchableExample.js).

**Comment by CusProjects** [comment]
@madox2 Yes, something like that, thanks .
