### ISSUE TITLE
MenuTrigger - triggerTouchable; props not set

### ISSUE THREAD

**Issue by andreiciceu** [instea/react-native-popup-menu#39]
Hello,

The `triggerTouchable` prop from `MenuTrigger` doesn't seem to update TouchableHighliht's props (as stated in the docs).

When I try 
`
          <MenuTrigger
            style={{paddingLeft: 10, paddingRight: 5, height: '100%', justifyContent: 'center'}}
            triggerTouchable={{hitSlop: {right: 5}}
          >
`
The hitSlop doesn't seem to change. tried also `underlayColor: 'red'`, but still no results.

RN: 0.47.2
react-native-popup-menu: 0.8.0

Many thanks!

**Comment by madox2** [comment]
Hi, you have to pass touchable props into [`customStyles`](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#custom-styles-1) property:

```javascript
<MenuTrigger
  customStyles={{
    triggerTouchable: {
      hitSlop: { right: 5 }
    }
  }}
>
```

**Comment by andreiciceu** [comment]
My bad in understanding the docs. Thank you ^^
