### ISSUE TITLE
Menu not working with react-native-router-flux 4

### ISSUE THREAD

**Issue by Hugainz** [instea/react-native-popup-menu#42]
### Problem:
[Basic Menu Example](https://github.com/instea/react-native-popup-menu/blob/master/examples/BasicExample.js) doesn't work on Android, giving only the following warning when the **Menu Trigger** text is pressed:

![image](https://user-images.githubusercontent.com/17356700/30269076-a17ac9ce-96df-11e7-98ae-3c024b4a7904.png)

Probably the same as  #41, but I decided to create a new issue since it might not be the same.

### Expected Behavior
Basic menu example works after simple copy-paste.

### Libraries versions: 
* react-native-popup-menu@0.8.1
* react-native@0.48.1
### Root Component Snippet:
```jsx
//...
import { MenuContext } from 'react-native-popup-menu';
//...

class App extends Component {
  //...

  render() {
     //...
    return (
      <Provider store={store}>
        <MenuContext style={{ flex: 1 }}>
          <Router />
        </MenuContext>
      </Provider>
    );
  }
}

AppRegistry.registerComponent('scDocsMobile', () => App);

export default App;
```

### Component w/ Menu:

This component is the initial component on the Router, so it's the first to render when the App boots up.

```jsx

//...
import {
  Menu,
  MenuOptions,
  MenuOption,
  MenuTrigger,
} from 'react-native-popup-menu';

export default class Testing extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Hello world!</Text>
        <Menu onSelect={value => console.log(`Selected number: ${value}`)}>
          <MenuTrigger text='Select option' />
          <MenuOptions>
            <MenuOption value={1} text='One' />
            <MenuOption value={2}>
              <Text style={{ color: 'red' }}>Two</Text>
            </MenuOption>
            <MenuOption value={3} disabled text='Three' />
          </MenuOptions>
        </Menu>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```

**Comment by sodik82** [comment]
thank you...  can you tell which version of RN have you used?

**Comment by sodik82** [comment]
Thank you. I have tried simplified example and seems to work:

      <Provider store={store}>
        <MenuContext style={{ flex: 1 }}>
          <Testing />
        </MenuContext>
      </Provider>

Maybe if you can share with us details about your used navigation (which library, sample setup)? Or maybe if you can confirm first if it works without the `Router`?

**Comment by Hugainz** [comment]
For navigation I'm using **react-native-router-flux@4.0.0-beta.21** with the following setup on Router:
```jsx
const RouterComponent = () => (
  <Router>
    <Scene hideNavBar>
      <Stack key="auth" initial>
        <Scene
          key="testing"
          component={Testing}
          title="Testing"
          initial
        />
      {/*... */} 
      </Stack>
    {/*... */} 
    </Scene>
  </Router>
);
```

**Comment by sodik82** [comment]
thank you - I can reproduce the bug now. We will need some time to fix it properly however here is small workaround - wrap your router definition so that it does not rerender like

      <Provider store={store}>
        <MenuContext style={{ flex: 1 }}>
          <StaticRenderer>
            <RouterComponent />
          </StaticRenderer>
        </MenuContext>
      </Provider>

example implementation of StaticRenderer

```
class StaticRenderer extends Component {
  shouldComponentUpdate() {
    return false;
  }
  render() {
    return React.Children.only(this.props.children)
  }
}
```

**Comment by Hugainz** [comment]
I'm fairly new to React Native, so forgive my ignorance when I ask you:
Will wrapping the router as suggested have any other (side-)effects?

**Comment by sodik82** [comment]
as far I have seen the bug - it has side effects (remounting of menu) if the router is not shielded from MenuContext. Unless you have something else "above" the router that might change the router definition somehow - it is safe to wrap router.

Right now we are working on refactoring of our internals so that such workarounds are not needed but we need more time for it.

**Comment by sodik82** [comment]
@Hugainz - new version `0.8.2` should work without any workarounds. can you confirm it?

**Comment by mohamed-alashry** [comment]
it's not working

**Comment by sodik82** [comment]
can you provide us more details? does it work with workaround? what error/unexpected behaviour do you get? more details about your setup?

**Comment by Hugainz** [comment]
@sodik82 I'm sorry for the late response but I can confirm it indeed works without the workaround for me. Cheers :+1:

**Comment by mohamed-alashry** [comment]
I will give a try again, thanks for the feedback.

**Comment by sodik82** [comment]
@mohamed-alashry - thanks. maybe it is unrelated problem (maybe #41 ). but if you have any more information about your problem we can resolve it.
