### ISSUE TITLE
TransformError: __DEV__ is not defined

### ISSUE THREAD

**Issue by dimonomid** [instea/react-native-popup-menu#5]
Hello,

I'm trying to use your module in React Native 0.26.3, but just when I import anything from `react-native-popup-menu`, I get this:
```
transformed 714/715 (100%)[node-haste] Encountered an error while persisting cache:
> ReferenceError: __DEV__ is not defined
>     at Object.<anonymous> (/home/dimon/projects/go/src/cesanta.com/mud/node_modules/react-native/Libraries/react-native/react-native.js:15:5)
>     at Module._compile (module.js:435:26)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at /home/dimon/projects/go/src/cesanta.com/mud/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:391:22
>     at Array.map (native)
> TransformError: /home/dimon/projects/go/src/cesanta.com/mud/node_modules/react-native-popup-menu/src/index.js: __DEV__ is not defined
```

Could you please give some clue?

**Comment by sodik82** [comment]
any chance it is somehow related to https://github.com/facebook/react-native/issues/7814 ? Do you use `.babelrc`?

**Comment by sodik82** [comment]
should be fixed with version 0.5.2

**Comment by mschipperheyn** [comment]
I use RN 0.24.1 and my build fails with ENOENT: no such file [...]/react-native-popup-menu/.babelrc (which isn't there). I have 0.5.2

**Comment by mschipperheyn** [comment]
<img width="354" alt="screen shot 2016-06-28 at 08 53 15" src="https://cloud.githubusercontent.com/assets/384959/16414404/cb15718a-3d0d-11e6-8b5f-c2c115a4d959.png">
0.5.2 with RN 0.24.1. Error occured after a clean node_modules && npm install and seems to have come out of nowhere.

**Comment by sodik82** [comment]
the file should not be there... can I assume that you have restarted also the RN packager?

**Comment by sodik82** [comment]
I was able to "reproduce" the problem when I have deleted node_modules and installed new version `0.5.2` without restarting RN packager.  The restart helped. I would say "standard" npm/packager issues :(
Does it works for you?

**Comment by mschipperheyn** [comment]
I resolved it w clean cache, delete build dir and hard reset of the simulator

**Comment by sodik82** [comment]
thanks
