### ISSUE TITLE
Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `ContextMenu`, expected `object`

### ISSUE THREAD

**Issue by allenmanning** [instea/react-native-popup-menu#55]
I'm seeing a warning when I open the popup.

```
ExceptionsManager.js:73 Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `ContextMenu`, expected `object`.
    in ContextMenu (created by MenuPlaceholder)
    in MenuPlaceholder (at MenuContext.js:190)
    in RCTView (at View.js:113)
    in View (at MenuContext.js:186)
    in MenuContext (at Main.js:40)
    in Provider (at Main.js:39)
    in main (at App.js:6)
    in App (at index.android.js:8)
    in verbmaster (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
```

```
react-native@0.50.3
react-native-popup-menu@0.9.0
```

I see style being set here:
https://github.com/instea/react-native-popup-menu/blob/master/src/MenuContext.js#L250

Thanks for maintaining this project!

**Comment by sodik82** [comment]
Strange, MenuContext does not have propTypes. Does it happen with "basic" setup or only when you use some combination of props?

**Comment by allenmanning** [comment]
I'll try a super basic setup and see if that has the same warning.

**Comment by allenmanning** [comment]
Here is the stack trace I'm working with:

    ExceptionsManager.js:73 Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `ContextMenu`, expected `object`.
    in ContextMenu (created by MenuPlaceholder)
    in MenuPlaceholder (at MenuContext.js:190)
    in RCTView (at View.js:113)
    in View (at MenuContext.js:186)
    in MenuContext (at Home.js:55)
    in Home (created by Connect(Home))
    in Connect(Home) (at navigationStore.js:313)
    in Wrapped (at SceneView.js:31)
    in SceneView (at CardStack.js:394)
    in RCTView (at View.js:113)
    in View (at CardStack.js:393)
    in RCTView (at View.js:113)
    in View (at CardStack.js:392)
    in RCTView (at View.js:113)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:436)
    in RCTView (at View.js:113)
    in View (at CardStack.js:365)
    in RCTView (at View.js:113)
    in View (at CardStack.js:364)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:187)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:216)
    in NavigationContainer (at Router.js:67)
    in App (at Router.js:88)
    in Router (at routes.js:35)
    in Routes (created by Connect(Routes))
    in Connect(Routes) (at Main.js:41)
    in Provider (at Main.js:40)
    in main (at App.js:6)
    in App (at index.android.js:8)
    in verbmaster (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

**Comment by allenmanning** [comment]
When I removed my custom renderer the issue went away, it is an issue with that.

**Comment by allenmanning** [comment]
I see what it is, I copied `ContextMenu` to adjust animation in my own customer renderer.  After doing a version update, my old forked context menu was causing this warning.  I'm looking for an animation that follows more of the style of material design.
