### ISSUE TITLE
there is a black point

### ISSUE THREAD

**Issue by happyming9527** [instea/react-native-popup-menu#6]
On android, before the menu is opened, there is a black point in the center of the menu scope.how to remove it?

**Comment by sodik82** [comment]
the popup menu has "opening animation". can it be the case?

and is it happening all the time or just sometimes? is it happening only in simulator/dev mode or also on real device/release version...

**Comment by happyming9527** [comment]
your android.demo.gif also show the problem. when you click the right top button, the point will show.maybe opening animation is the problem.

**Comment by sodik82** [comment]
thanks for info. will check it soon.

**Comment by sodik82** [comment]
imo it is opening animation together with shadows. in v `0.5.1` we have added new "non-animated" menu renderer. See `ExtensionExample` for more details.

Can you check if "black point" disappears?
