### ISSUE TITLE
How to set width of  MenuOptions group?

### ISSUE THREAD

**Issue by daotien0887** [instea/react-native-popup-menu#72]
I try to set width of MenuOption group but it alway set by screen/2.
I try set style for MenuOptions but it only for MenuOption of group.
<MenuOptions
                                    style={{
                                        height: deviceHeight / 2,
                                        width: deviceWidth / 5,
                                        backgroundColor: colors.green,
                                        paddingRight: 10,
                                        marginRight: 10,
                                    }}
                                >

**Comment by daotien0887** [comment]
I found setting is in ContextMenu.js but how to set it on code?
options: {
    position: 'absolute',
    borderRadius: 2,
    backgroundColor: 'white',
    **width: 200,**
...

**Comment by ErnesII** [comment]
> 
> 
> I try to set width of MenuOption group but it alway set by screen/2.
> I try set style for MenuOptions but it only for MenuOption of group.
> <MenuOptions
> style={{
> height: deviceHeight / 2,
> width: deviceWidth / 5,
> backgroundColor: colors.green,
> paddingRight: 10,
> marginRight: 10,
> }}
> >

Hi there, I just started using this nice Component, I have made my own Dropdown based on this component, I am pretty sure with this you can change the width of the popup:
`<MenuOptions customStyles={{optionsContainer: width: 100}} />`
