### ISSUE TITLE
how to control the popmenu's position?

### ISSUE THREAD

**Issue by shapenlone** [instea/react-native-popup-menu#8]
when i clicked menu trigger,
how can i control the menu default position in the screen?

thanks

**Comment by madox2** [comment]
Hi, do you want to set fix position of menu or you want to compute position according to window and menu dimensions?
Notice that you can implement your own menu renderer which is described in [Custom renderer](https://github.com/instea/react-native-popup-menu/blob/master/doc/extensions.md#custom-renderer) section.

**Comment by shapenlone** [comment]
thx u very much
