### ISSUE TITLE
Move the ContextMenu popup to above of keyboard

### ISSUE THREAD

**Issue by SurajMDurgad** [instea/react-native-popup-menu#83]
Hi,
 I'm using Context Menu as my popup which has a custom view.
Here is my code -
```
<Menu>
	
<MenuTrigger 
style={{ alignItems:'center',
lineHeight: normalize(20),
borderBottomWidth: 2,
borderBottomColor: '#BBBBBB',
marginLeft: normalize(15),
marginRight:normalize(30)}}>

<Text>{selected_location}</Text>

</MenuTrigger>

<MenuOptions optionsContainerStyle={{flex:1, width: 285, marginLeft: 11, marginTop: 5}}>

<ScrollView style={{ maxHeight: 200 }}>

<MenuOption>

<Availability
data={rowData.each_model}
onSelect={this.onSelect.bind(this)}	/>

</MenuOption>

</ScrollView>

</MenuOptions>

</Menu>
```
There is a input field in Availability component.
When I click on that, the keyboard popups hiding the popup.
Is there any way where I can give the position to the popup when the keyboard is opened. 
I'm using Keyboard listener where in I can give a position to the component.

**Comment by sodik82** [comment]
hi. Handling of "keyboard overlapping" is usually general problem in mobile apps. context menu does not any special handling in that regard - so I would suggest you to consider using https://facebook.github.io/react-native/docs/keyboardavoidingview.html or any appropriate techniques to handle the problem.

if you want to give a special position to the menu itself, it is still possible to create your own renderer ( https://github.com/instea/react-native-popup-menu/blob/master/doc/extensions.md#custom-renderer ) where you have almost complete control over the menu.
