### ISSUE TITLE
MenuComponent must be an ancestor of MenuProvider

### ISSUE THREAD

**Issue by BrianJVarley** [instea/react-native-popup-menu#84]
react-native version: react-native: 0.42.0
package: react-native-popup-menu

Issue:
I didn't see this issue already logged in the repo issues so opening a new one here for review.
As explained here https://github.com/instea/react-native-popup-menu#basic-usage to `Wrap your application inside MenuProvider`

Wrapping my main entry point in app MenuProvidercauses the error:
`MenuComponent must be an ancestor of MenuProvider`

Code Snippet:

```
return (
      <MenuProvider>
      <View style={{flex: 1}}>
        <NavigationViewContainer />
        {__DEV__ && <DeveloperMenu />}
      </View>
      </MenuProvider>

    );
```

Screenshot:

![screenshot_20180328-215810](https://user-images.githubusercontent.com/6731968/38056707-21bee0ac-32d5-11e8-8df7-68d6c9736e2f.png)

**Comment by sodik82** [comment]
In most cases wrapping your app into `MenuProvider` is the best option (only exception so far was usage with [Modal](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#menuprovider)).

Basically (as error says) the `Menu` component must be ancestor of `MenuProvider` - and it seems that it is not happening - maybe it has something your navigation (which one do you use)? Can it have something with native implementation?

**Comment by BrianJVarley** [comment]
Turns out I didn't have `MenuProvider` as the ancestor at the app entry point..reloading and placing the element as the highest ancestor fixed the render issue.

**Comment by Leena1440** [comment]
**Add MenuContext in imports**
   import { MenuContext } from 'react-native-popup-menu';
**Wrap the code in the <MenuContext> Like,**
  <MenuContext style={styles.container}>
    ...
  </MenuContext style>
