### ISSUE TITLE
Menu Options Container constantly rerenders in slightly different x position 

### ISSUE THREAD

**Issue by avertin** [instea/react-native-popup-menu#85]
**Observed behavior:** On Android Pixel, the menu options container would jump a few pixels back and forth very quickly. As a result, the menu edge appears to shimmy/giggle.  The menu width was set to 300. I suspect that the specific combination of position and width was causing the issue because the issue went away when the phone was rotate to landscape. 

![shimmy](https://user-images.githubusercontent.com/11411307/38059687-4abbc0da-329c-11e8-8b9c-4ac4ff991f7d.gif)

Logging the layouts prop that is passed to the NotAnimatedContextMenu renderer reveals that the x position and width vary slightly every time. The x-position and width continue to oscillate indefinitely until the menu is closed. The function is called repeatedly: 

![screen shot 2018-03-28 at 3 29 08 pm](https://user-images.githubusercontent.com/11411307/38059828-e596f412-329c-11e8-9459-c4f4e6d01384.png)

**Expected behavior:** The x-position and the width should not change when the menu has remained fixed. 

**Workaround:** We defined a custom renderer for the NotAnimatedContextWindow that only updates the position if the difference between the previous x position and new x position is greater than 1. 
```
let prevLeftPosition;
export function CustomNotAnimatedContextMenu(props) {
  const { style, children, layouts, ...other } = props;
  const position = ContextMenu.computePosition(layouts);

  let stablePosition;
  if (!prevLeftPosition || Math.abs(position.left - prevLeftPosition) > 1) {
    prevLeftPosition = position.left;
    stablePosition = position;
  } else {
    stablePosition = { top: position.top, left: prevLeftPosition };
  }

  return (
    <View {...other} style={[ContextMenu.styles.options, style, stablePosition]}>
      {children}
    </View>
  );
}
```

**Comment by avertin** [comment]
Using `version "0.12.2"`

**Comment by sodik82** [comment]
Thanks for report. 

It looks like the menu content somehow changes with each rerender (caused by updated layout). Is there anything special about your Menu code snippet? Do you set fixed width style for menu option container?

Is this specific for Android Pixel? (maybe due to high pixel density?)

**Comment by avertin** [comment]
I would like to just use the built in `NotAnimatedContextMenu`, but it has the bug described above. My code snippet is the same code as the built in `NotAnimatedContextMenu` except that it doesn't update the x position if it hasn't changed much. 

So far this has only reproduced on Android Pixel. 

I am setting the fixed width on the menu option**s** container:

```
optionsContainer: {
    width: 300
  }
```

**Comment by sodik82** [comment]
hm... strange - since you are setting fixed width, why onLayout report (ever changing) fractional numbers. 

It would be interesting if something like https://facebook.github.io/react-native/docs/pixelratio.html#roundtonearestpixel would help in your CustomNotAnimatedContextMenu (e.g. fixing x,y and/or width)

**Comment by avertin** [comment]
I initially misunderstood where you were suggesting using `roundToNeartestPixel`.  Thanks for the suggestion.

This fixed the issue: 
```
optionsContainer: {
    width: PixelRatio.roundToNearestPixel(300)
}
```

**Comment by avertin** [comment]
The rounded value for Android Pixel was `300.1904761904762`
