### ISSUE TITLE
Warning: isMounted(...) is deprecated in plain Javascript Classes

### ISSUE THREAD

**Issue by fallenner** [instea/react-native-popup-menu#93]
Warning: isMounted(...) is deprecated in plain Javascript Classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

Version:

react: 16.3.2
react-native: 0.55.2
react-native-popup-menu: 0.12.5

**Comment by sodik82** [comment]
We don't use any `isMounted` ... My guess is that it is somewhere inside RN directly. Maybe check hint about disabling YellowBox as mentioned in https://github.com/react-navigation/react-navigation/issues/3956

If anyone has more knowledge about this problem, let us know.

**Comment by fallenner** [comment]
@sodik82   I  also have not found 'isMounted' in react-native-popup-menu. However, I open the menu by 'this.$refs.xxx.open()', The Warning will appear....  

this is My code。

<TouchableWithoutFeedback onPress={() => this.refs.reportMenu.open()}>
......
</TouchableWithoutFeedback>


<Menu renderer={SlideInMenu} ref={'reportMenu'}>
                    <MenuTrigger/>
                    <MenuOptions>
                        <MenuOption text={'report'}
                                    customStyles={{optionText: styles.menuOptionText}}
                                    onSelect={() => this.props.navigation.navigate('Report', {code: 'report'})}/>
                        <MenuOption text={'handle'} customStyles={{optionText: styles.menuOptionText}}
                                    onSelect={() => this.props.navigation.navigate('Handle', {code: 'handle'})}/>
                    </MenuOptions>
 </Menu>

**Comment by fallenner** [comment]
@sodik82  I also have not found 'isMounted' in react-native-popup-menu. However, I open the menu by 'this.$refs.xxx.open()', The Warning will appear....

This My Code.

` <Menu renderer={SlideInMenu} ref={'reportMenu'}>
                    <MenuTrigger/>
                    <MenuOptions>
                        <MenuOption text={'Report'}
                                    customStyles={{optionText: styles.menuOptionText}}
                                    onSelect={() => this.props.navigation.navigate('Report', {code: 'report'})}/>
                        <MenuOption text={'Handle'} customStyles={{optionText: styles.menuOptionText}}
                                    onSelect={() => this.props.navigation.navigate('Handle', {code: 'handle'})}/>
                    </MenuOptions>
 </Menu>`

**Comment by sodik82** [comment]
I can confirm that it is happening but as same is happening also in `react-navigation` thus I expect the problem is directly in RN (as suggested in https://github.com/react-navigation/react-navigation/issues/3956#issuecomment-381794235 )

**Comment by isaachinman** [comment]
Experiencing this issue as well, not using `react-navigation` but rather `react-native-navigation`. Any ideas?

**Comment by ahmedu007** [comment]
Im using `react-router-navigation` and still see these warnings

**Comment by ahmedu007** [comment]
I had the same issue, It went away after updating React native to latest version `0.55.4`
