### ISSUE TITLE
undefined is not a function (evaluating '_react3.default.forwardRef(enhanceForwardRef)')

### ISSUE THREAD

**Issue by AnthonyNTK** [instea/react-native-popup-menu#96]
Development Env:
react: 16.3.0-alpha.1
react-native: 0.54.0
react-native-popup-menu: 0.13.0
gradle build 3.1.0
gradle wrapper 4.4

Deployment Env:
Physical Device: Sony Xperia X
Android SDK: 27

Expected outcome:
Main screen rendered with menu button

Actual outcome:
Red box error

Code snippet:
```
       <MenuProvider style={{flexDirection: 'column', padding: 30}}>
          <Menu>
            <MenuTrigger>
              <Image source={require('../../../../images/ic_add.png')} style={{opacity: opacity}} />
            </MenuTrigger>
            <MenuOptions>
              <MenuOption
                text="Upload image"
                onSelect={this.handleImagePicker}/>
              <MenuOption
                text="Upload file"
                onSelect={this.handleFilePicker}/>
            </MenuOptions>
          </Menu>
        </MenuProvider>
```

TrackStack:
warp
C:\User\UU\ChatApp\node_modules\react-native-popup-menu\src\with-context.js:
35:32

unknown
C:\User\UU\ChatApp\node_modules\react-native-popup-menu\src\Menu.js
150:29

If you need more info, i will make a screen shot at below comment

**Comment by sodik82** [comment]
hi there... popup menu 0.13 has minimal requirement RN 0.55. Please use older 0.12.x version

**Comment by AnthonyNTK** [comment]
Thanks for the quick reply! Got the fix now
