### ISSUE TITLE
Error: (0 , _react2.createContext) is not a function

### ISSUE THREAD

**Issue by khushboogupta1** [instea/react-native-popup-menu#98]
Below is my code. I am having a listView. I want to open a popup menu when user long press on "name". But i am getting error of createContext. Please provide me fix.

          import {
             MenuContext,
             Menu,
             MenuOptions,
             MenuOption,
             MenuTrigger,
        } from 'react-native-popup-menu';

       render(){
           ...
           return(
                 <View style={{ flex: 1, flexDirection: 'row' }} >
                <MenuContext>
                  <TouchableWithoutFeedback onLongPress = {this.openMenu}>
                          <Text style={styles.textViewContainer} >{rowData.Ad_name}</Text>
                          <Menu ref={c => (this.menu = c)}>
                            <MenuTrigger text = "Select Action.." />
                            <MenuOptions>
                                <MenuOption onSelect = {() => this.onEditCampaignAction.bind(this, rowData.campaign_id)}>
                                    {rowData.Status == '0' ?
                                        <TouchableOpacity
                                            style={styles.SubmitButtonStyle}
                                            activeOpacity={.5}
                                            onPress={this.onEditCampaignAction.bind(this, rowData.campaign_id)}>
                                            <FontAwesomeIcon name='pencil' style={styles.icon} />
                                        </TouchableOpacity>
                                        :
                                        <TouchableOpacity
                                            style={styles.SubmitButtonStyle}
                                            activeOpacity={.5}
                                            onPress={this.onViewDetailsAction.bind(this, rowData.campaign_id)}>
                                            <FontAwesomeIcon name='eye' style={styles.icon} />
                                        </TouchableOpacity>
                                    }
                                </MenuOption>
                            </MenuOptions>
                        </Menu>
                  </TouchableWithoutFeedback>
                </MenuContext>
             </View>
           );
       }

 Any help would be much appreciated.

**Comment by steventnorris-40AU** [comment]
Having the same problem. Any new info on this?

**Comment by steventnorris-40AU** [comment]
Actually, I believe this may be a case of versioning. I was using the latest of this repo, which requires React Native 0.55+, but my React Native was at 0.52.1. I downgraded to the version prior (^0.12), and the import functions. May want to consider supporting both the new React context API by default but fallback to the old API if the new one fails.

**Comment by sodik82** [comment]
Yes, indeed - `0.13` version requires RN 0.55. We also warn about that in our code but Red box takes precedence :/ 
Together with new context API we have upgraded to new React lifecycle methods - supporting both ways (old and new) looks impractical.

**Comment by steventnorris-40AU** [comment]
Fair enough. I should have paid a little closer attention to dependency requirements. Thanks for the response. Works fine with v0.12.

**Comment by sodik82** [comment]
Hopefully more meaningful error (instead of simple warning) will help https://github.com/instea/react-native-popup-menu/commit/66b347f04422dffa3acaadceff910385866cfabd
