### ISSUE TITLE
Add Background color to area with no options

### ISSUE THREAD

**Issue by FernandoCCNunes** [instea/react-native-popup-menu#99]
Hi, i have tested every single style from your library (amazing one btw) and i couldn't find how to add a black background with some transparency when the Menu is called to darken the space where there is no options rendered.
I decided to post this here because i can't find any questions about it anywhere and so i was wondering if it was actually possible, I even went through your code to see if i could manually set it but no luck there.
I apreciate your help.
Thanks

**Comment by sodik82** [comment]
Hi,

are we talking about Backdrop? Can you try our example

https://github.com/instea/react-native-popup-menu/blob/master/examples/StylingExample.js#L130

Or maybe I just haven't understand you correctly?

**Comment by FernandoCCNunes** [comment]
That's exactly it, I don't know why I thought it had something to do with on Back Button pressed styling and stuff like that, thank you very much, appreciate it
